### ISSUE TITLE
Test `websocketsbinary` causes exception printed to console in Chrome

### ISSUE THREAD

**Issue by lukashlavacka** [Modernizr/v3.modernizr.com#14]
I have noticed that running `websocketsbinary` test in Chrome 42.0.2311.152 causes an exception to be printed to console:
`WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED`

Even though the responsible code is wrapped in try/catch block the exception is never caught by the catch block.

I found some resources about similar issue on StackOverflow: [How to catch `WebSocket connection to...` exception](http://stackoverflow.com/questions/25779831)

**Comment by ryanseddon** [comment]
Can you file this on modernizr/modernizr. I just tried in Chrome 43 and didn't see the error.
