### ISSUE TITLE
Can't download or generate

### ISSUE THREAD

**Issue by mattkemp** [Modernizr/v3.modernizr.com#7]
The download button isn't doing anything, and the generate doesn't seem to be creating runnable code. Also the "Don't Minify Source" checkbox still results in minified code - just the comments are a little more long-form.

I'm just trying to get the videoautoplay test - nothing else.

**Comment by ryanseddon** [comment]
Is this still the case? I pushed some changes about 2 weeks ago as I noticed issues myself, can you try again please.

**Comment by FlashJunior** [comment]
it works for me:
OSX 10.10: Safari, Chrome, Firefox
Win 7: IE11, Chrome, Firefox

**Comment by ryanseddon** [comment]
Ok closing, @mattkemp if it's still broken for you please re-open.

**Comment by d7omee** [comment]
Trrr
